# site properties and page defaults
title: MOFAI
subtitle: Mathematics of Artificial Intelligence
description: Mathematics of Artificial Intelligence explores the foundational algorithms and theories driving machine learning, optimization, and data-driven decision-making systems.
header: images/background.jpg
footer: images/background.jpg
proofer: false

# site social media and other links
links:
  email: zahra.monfared@iwr.uni-heidelberg.de
  orcid: 0049-06221-5419001
  google-scholar: citations?user=OPUIwIoAAAAJ&hl=en&oi=ao
  github: MahshidBaharifar
  twitter: ---
  youtube: ---

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
